[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
remappings = [
    "@ensdomains/contracts-v2/=lib/contracts-v2/contracts/src/",
    "@openzeppelin/contracts/=lib/contracts-v2/contracts/lib/openzeppelin-contracts/contracts/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
